a = input().strip()
b = input().strip()

print(float(a) + float(b))
print(f'{float(a):.1f}' + b)
print(float(a) * float(b))
print(str(float(a)) * int(b))
print(float(a)/float(b))
print(float(a) // float(b))
print(float(a) ** float(b))
print(float(a) % float(b))